cars/urls.py
from django.urls import path

from cars.views import ModelsView, add_to_wishlist, WishlistModelListView

app_name = 'models'

urlpatterns = [
        path('wishlist/', WishlistModelListView.as_view(), name='wishlist'),
        path('wishlist/<int:pk>/', add_to_wishlist, name='add-wishlist'),
        path('', ModelsView.as_view(), name='product'),
]

form/urls.py
from django.urls import path
from cars.views import HomeView
from form.views import FormaView

app_name = 'homes'

urlpatterns = [
    path('', FormaView.as_view(), name="form"),
]

home/urls.py
from django.urls import path

from cars.views import HomeView

app_name = 'home'

urlpatterns = [
    path('home/', HomeView.as_view(), name='index'),
]

jocar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

from cars.views import HomeView, ModelsView, add_to_wishlist

urlpatterns = [
    path('accounts/', include('registration.backends.default.urls')),
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('models/', include('cars.urls', namespace='products')),
    path('home/', include('home.urls', namespace='index')),
    path('', include('form.urls', namespace='homes')),


)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from django.db import models


class CarModel(models.Model):
    model = models.CharField(max_length=99, null=True)
    image = models.FileField(upload_to='cars_image', null=True)
    volume = models.CharField(max_length=99, null=True)
    power = models.CharField(max_length=99, null=True)
    transmission = models.CharField(max_length=99, null=True)
    engine = models.CharField(max_length=99, null=True)
    fuel = models.CharField(max_length=99, null=True)
    drive_unit = models.CharField(max_length=99, null=True)
    overclocking = models.CharField(max_length=99, null=True)
    consumption = models.CharField(max_length=99, null=True)
    max_speed = models.CharField(max_length=99, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def get_from_wishlist(request):
        wishlist = request.session.get('wishlist', [])
        return CarModel.objects.filter(pk__in=wishlist)

    def __str__(self):
        return self.model

    class Meta:
        verbose_name = 'car_spetification'
        verbose_name_plural = 'cars_spetifications'

form/models.py
from django.db import models

# Create your models here.

cars/views.py
from django.http import JsonResponse
from rest_framework.response import Response
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from cars.models import CarModel


class HomeView(ListView):
    template_name = 'index.html'
    queryset = CarModel.objects.all()
    context_object_name = 'lists'


class ModelsView(ListView):
    template_name = 'models.html'
    queryset = CarModel.objects.all()
    context_object_name = 'models'


class WishlistModelListView(ListView):
    template_name = 'wishlist.html'
    paginate_by = 7

    def get_queryset(self):
        return CarModel.get_from_wishlist(self.request)


def add_to_wishlist(request, pk):
    try:
        product = CarModel.objects.get(pk=pk)
    except CarModel.DoesNotExist:
        return Response(data={'status': False})
        # if not wishlist:
        #     wishlist = []
    wishlist = request.session.get('wishlist', [])
    if product.pk in wishlist:
        wishlist.remove(product.pk)
        data = {'status': True, 'added': False}
    else:
        wishlist.append(product.pk)
        data = {'status': True, 'added': True}
    request.session['wishlist'] = wishlist

    return JsonResponse(data)

form/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class FormaView(TemplateView):
    template_name = 'form.html'

home/views.py
from django.shortcuts import render

# Create your views here.

templates/form.html
{% load static %}
{% load tags %}
{% block content %}
<style>
/* Style all input fields */
body{
  background: url(/static/images/losz.jpeg);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  height: 100%;
}
input {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
}

/* Style the submit button */
input[type=submit] {
    background-color: #4CAF50;
    color: white;
}

/* Style the container for inputs */
.container {
    padding: 20px;
}

/* The message box is shown when the user clicks on the password field */
#message {
    display:none;
    background: #f1f1f1;
    color: #000;
    position: relative;
    padding: 20px;
    margin-top: 0px;
    border-radius: 10px;
    transition: transform 10s;
}

#message p {
    padding: 10px 35px;
    font-size: 18px;
}


#message2 {
    display:none;
    background: #f1f1f1;
    color: #000;
    position: relative;
    padding: 20px;
    margin-top: 0px;
    border-radius: 10px;
    transition: transform 10s;
}

#message2 p {
    padding: 10px 35px;
    font-size: 18px;
}

/* Add a green text color and a checkmark when the requirements are right */
.valid {
    color: green;
}

.valid:before {
    position: relative;
    left: -35px;
    content: "✔";
}

/* Add a red text color and an "x" when the requirements are wrong */
.invalid {
    color: red;
}

.invalid:before {
    position: relative;
    left: -35px;
    content: "✖";
}


.valid2 {
    color: green;
}

.valid2:before {
    position: relative;
    left: -35px;
    content: "✔";
}


.invalid2 {
    color: red;
}

.invalid2:before {
    position: relative;
    left: -35px;
    content: "✖";
}
</style>
</head>
<body>


<div class="container">
  <div class="form" style="background-color: rgba(0, 0, 0, .7);width: 50%;margin: auto;margin-top: 12%;">
    <h3 style="text-align: center;color:#fff;font-size:20px;font-weight:bold;font-family:Arial, Helvetica, sans-serif;padding: 20px 0px; ">Добро пожаловать на наш сайт <br> Jocars</h3>
    <form action="{% url 'home:index' %}" style="margin:auto;padding: 20px;">
      <label for="usrname" style="color: #fff;font-size:16px;font-weight:500;font-family:Arial, Helvetica, sans-serif">Username</label>
      <input type="text" id="usrname" name="usrname" required>

      <label for="psw" style="color: #fff;font-size:16px;font-weight:500;font-family:Arial, Helvetica, sans-serif">Password</label>
      <input type="password" id="psw" name="psw"  pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required>
      <div id="message">
        <h3>Пароль должен содержать</h3>

        <p id="capital" class="invalid">Минимум <b>1 заглавная буква</b></p>
        <hr>
        <p id="number" class="invalid">Минимум <b>1 цифра</b></p>
        <hr>
        <p id="length" class="invalid">Минимум <b>8 символов</b></p>

        <!-- <p id="letters" class="invalid"> <b></b></p> -->
      </div>
      <label for="email" style="color: #fff;font-size:16px;font-weight:500;font-family:Arial, Helvetica, sans-serif">Email</label>
      <input type="text" id="email" name="email" title="email" required>
      <div id="message2">
        <p id="email2" class="invalid2">Используйте правильный формат почты <b>("@gmail.com")</b> </p>
      </div>
      <input type="submit" value="Submit">
    </form>
  </div>

</div>



<script>
var myInput = document.getElementById("psw");
var capital = document.getElementById("capital");
var number = document.getElementById("number");
var length = document.getElementById("length");
var letter = document.getElementById("letter");
var myEmail = document.getElementById("email");
var email2 = document.getElementById("email2")
// var email = /^[a-z0-9](\.?[a-z0-9]){5,}@g(oogle)?mail\.com$/;

// When the user clicks on the password field, show the message box
myEmail.onfocus = function() {
    document.getElementById("message2").style.display = "block";
}

// When the user clicks outside of the password field, hide the message box
myEmail.onblur = function() {
    document.getElementById("message2").style.display = "none";
}


// When the user clicks on the password field, show the message box
myInput.onfocus = function() {
    document.getElementById("message").style.display = "block";
}

// When the user clicks outside of the password field, hide the message box
myInput.onblur = function() {
    document.getElementById("message").style.display = "none";
}

// When the user starts to type something inside the password field
myEmail.onkeyup = function() {
  var emails = /@gmail.com/g;
  if(myEmail.value.match(emails)) {
    email2.classList.remove("invalid2");
    email2.classList.add("valid2");
  } else {
    email2.classList.remove("valid2");
    email2.classList.add("invalid2");
  }
}

myInput.onkeyup = function() {
  // Validate capital letters
  var upperCaseLetters = /[A-Z]/g;
  if(myInput.value.match(upperCaseLetters)) {
    capital.classList.remove("invalid");
    capital.classList.add("valid");
  } else {
    capital.classList.remove("valid");
    capital.classList.add("invalid");
  }

  console.log("error")

  // Validate numbers
  var numbers = /[0-9]/g;
  if(myInput.value.match(numbers)) {
    number.classList.remove("invalid");
    number.classList.add("valid");
  } else {
    number.classList.remove("valid");
    number.classList.add("invalid");
  }

  // Validate length
  if(myInput.value.length >= 8) {
    length.classList.remove("invalid");
    length.classList.add("valid");
  } else {
    length.classList.remove("valid");
    length.classList.add("invalid");
  }

}
</script>
{% endblock %}

templates/index.html
{% extends 'layouts/base.html' %}
{% load i18n %}
{% load tags %}
{% load static %}
{% block content %}
  <style>
.nav-link{
    font-weight: bold;
    font-family: "Source Sans Pro";
    color: #000;
    text-transform: uppercase;
}
.group {
  position:relative; 
  margin-bottom:45px; 
}
input 				{
  font-size:18px;
  padding:10px 10px 10px 5px;
  display:block;
  width:300px;
  border:none;
  border-bottom:1px solid #757575;
}
input:focus 		{ outline:none; }

/* LABEL ======================================= */
label 				 {
  color:#999; 
  font-size:18px;
  font-weight:normal;
  position:absolute;
  pointer-events:none;
  left:5px;
  top:10px;
  transition:0.2s ease all; 
  -moz-transition:0.2s ease all; 
  -webkit-transition:0.2s ease all;
}

/* active state */
input:focus ~ label, input:valid ~ label 		{
  top:-20px;
  font-size:14px;
  color:#5264AE;
}

/* BOTTOM BARS ================================= */
.bar 	{ position:relative; display:block; width:300px; }
.bar:before, .bar:after 	{
  content:'';
  height:2px; 
  width:0;
  bottom:1px; 
  position:absolute;
  background:#5264AE; 
  transition:0.2s ease all; 
  -moz-transition:0.2s ease all; 
  -webkit-transition:0.2s ease all;
}
.bar:before {
  left:50%;
}
.bar:after {
  right:50%; 
}

/* active state */
input:focus ~ .bar:before, input:focus ~ .bar:after {
  width:50%;
}

/* HIGHLIGHTER ================================== */
.highlight {
  position:absolute;
  height:60%; 
  width:100px; 
  top:25%; 
  left:0;
  pointer-events:none;
  opacity:0.5;
}

/* active state */
input:focus ~ .highlight {
  -webkit-animation:inputHighlighter 0.3s ease;
  -moz-animation:inputHighlighter 0.3s ease;
  animation:inputHighlighter 0.3s ease;
}

/* ANIMATIONS ================ */
@-webkit-keyframes inputHighlighter {
	from { background:#5264AE; }
  to 	{ width:0; background:transparent; }
}
@-moz-keyframes inputHighlighter {
	from { background:#5264AE; }
  to 	{ width:0; background:transparent; }
}
@keyframes inputHighlighter {
	from { background:#5264AE; }
  to 	{ width:0; background:transparent; }
}

p {
            margin-bottom: 7px;
        }
        
        .btn:focus {
            box-shadow: none;
        }
        .btn-12{
  position: relative;
  right: 20px;
  bottom: 20px;
  border:none;
  box-shadow: none;
  line-height: 42px;
  -webkit-perspective: 230px;
  perspective: 230px;
}
.btn-12 span {
  background: rgb(0,172,238);
background: linear-gradient(0deg, rgba(0,172,238,1) 0%, rgba(2,126,251,1) 100%);
  display: block;
  position: absolute;
  width: 180px;
  height: 40px;
  box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
   7px 7px 20px 0px rgba(0,0,0,.1),
   4px 4px 5px 0px rgba(0,0,0,.1);
  border-radius: 5px;
  margin:0;
  text-align: center;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-transition: all .3s;
  transition: all .3s;
}
.btn-12 span:nth-child(1) {
  box-shadow:
   -7px -7px 20px 0px #fff9,
   -4px -4px 5px 0px #fff9,
   7px 7px 20px 0px #0002,
   4px 4px 5px 0px #0001;
  -webkit-transform: rotateX(90deg);
  -moz-transform: rotateX(90deg);
  transform: rotateX(90deg);
  -webkit-transform-origin: 50% 50% -20px;
  -moz-transform-origin: 50% 50% -20px;
  transform-origin: 50% 50% -20px;
}
.btn-12 span:nth-child(2) {
  -webkit-transform: rotateX(0deg);
  -moz-transform: rotateX(0deg);
  transform: rotateX(0deg);
  -webkit-transform-origin: 50% 50% -20px;
  -moz-transform-origin: 50% 50% -20px;
  transform-origin: 50% 50% -20px;
}
.btn-12:hover span:nth-child(1) {
  box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
   7px 7px 20px 0px rgba(0,0,0,.1),
   4px 4px 5px 0px rgba(0,0,0,.1);
  -webkit-transform: rotateX(0deg);
  -moz-transform: rotateX(0deg);
  transform: rotateX(0deg);
}
.btn-12:hover span:nth-child(2) {
  box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
   7px 7px 20px 0px rgba(0,0,0,.1),
   4px 4px 5px 0px rgba(0,0,0,.1);
 color: transparent;
  -webkit-transform: rotateX(-90deg);
  -moz-transform: rotateX(-90deg);
  transform: rotateX(-90deg);
}
  </style>
  
    <!-- top -->
    <div class="top" id="header">
        <!-- навиигация  -->

        <header>
            <div class="container">
                <div class="row">
                    <div class="col-5">
                        <h3 class="source-sans">{% trans 'Аренда авто' %}<h1 style="color: #fff;font-size: 30px;"><span>Jocar auto</span> - {% trans 'для тех, кто ценит время и деньги' %}.</h1>
                        </h3>
                        <br>
                        <p style="margin-left: 10%"><img src="{% static '/images/cars.png' %}" style="width: 10%;color: red;position: absolute;left: 0px;" alt="">{% trans 'Выбрать автомобиль' %} <br> <span > {% trans 'автомобиль в наличии' %}</span></p>
                            <h3 style="font-size: 20px;">{% trans 'Компания' %} <span class="source-sans">JocarAuto</span> <br> {% trans 'предлагает' %}</h3>
                            <p class="font-weight-bold">1-3 {% trans 'дня' %} 23000 {% trans 'руб' %}</p>
                            <p class="font-weight-bold">4-7 {% trans 'дней' %} 20000 {% trans 'руб' %}</p>
                            <p class="font-weight-bold">8-14 {% trans 'дней' %} 17000 {% trans 'руб' %}</p>
                    </div>
                    <div class="col-7">
                       
                    </div>
                </div>
            </div>
        </header>
    </div>
    <!-- модели авто -->
    <main class="cours" id="models">
        <div class="container">
             <h2 class="title font-weight-bold " style="text-align: center;margin: 20px" >
                   {% trans 'Наши топовые модели автомобилей' %}
                </h2>
            <div class="row">

                <!-- первая модель авто-->
                   {% for product in lists|slice:":2" %}
                         <div class="col-6">

                                    <div class="card" style="width: 95%; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
                                    <img class="card-img-top" src="{{ product.image.url }}" style="width: 100%;height: 220px" alt="Card image cap">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ product.model }}</h5>
                                        <p class="card-text">
                                            {% trans 'Характеристики' %}:
                                            <p> {% trans 'Объем' %} – {{ product.volume}}</p>
                                              <p>{% trans 'Мощность' %} - {{ product.power}}</p>
                                              <p>{% trans 'Коробка' %} - {{ product.transmission}}</p>
                                              <p>{% trans 'Тип двигателя' %} - {{ product.engine}}</p>
                                              <p>{% trans 'Топливо' %} - {{ product.fuel}}</p>
                                              <p>{% trans 'Привод' %} - {{ product.drive_unit}}</p>
                                              <p>{% trans 'Разгон' %} - {{ product.overclocking}}</p>
                                              <p>{% trans 'Расход' %} – {{ product.consumption}}</p>
                                              <p>{% trans 'Макс.скорость' %}, км/ч – {{ product.max_speed}}</p>
                                        </p>
                                      <a onclick="add_to_wishlist(this, {{ product.pk }})" class="card-link">
                                        {% if product|in_wishlist:request %}
                                        <button class="btn btn-like2" type="submit"><img src="{% static './images/red_active.svg' %}"
                                                                                     alt=""></button>
                                        {% else %}
                                        <button class="btn btn-like2" type="submit"><img src="{% static './images/like.svg' %}" alt="">
                                        </button>
                                        {% endif %}
                                    </a>
                                        <a href="/models"> <button data-toggle="modal" data-target="#exampleModal" class="btn btn-12" style="margin: 30px 0 20px 20px; font-weight: bold; font-size: 15px; color: #fff; "><span>Все продукты</span><span>Все продукты</span></button></a>
                            </div>
                      </div>

                        </div>
                    {% endfor %}
            </div>
           <a href="/models" style="text-decoration: none;"><button class="btn btn-outline-primary mt-3 text-center" style="margin: auto;display:block">{% trans 'Посмотреть еще' %}</button></a>
        </div>
    </main>
    <!-- контакты -->
    <main class="categories" id="contacts">
        <div class="container"> 
           
          <div class="row" style="margin-bottom: 60px; padding-bottom: 30px;">
            <div class="col-md-12">
            </div>
            <div class="col-md-7">
                <br>
              <div class="box" style="display: flex;">
                <i class="bx bx-like" style="font-size: 40px; margin-top: 10px;" ></i>
              <h3 style="margin-top: 10px; margin-left: 30px;">{% trans 'Гарантии' %}</h3>
              </div>
              <div class="box1" style="display: flex; margin-top: 50px; ">
                <i class="bx bxs-car-garage" style="font-size: 40px; margin-top: 10px;" ></i>
              <h3 style="margin-top: 10px; margin-left: 30px;">{% trans 'Качество и профессианализм' %}</h3>
              </div>
              <div class="box" style="display: flex; margin-top: 50px;">
                <i class="bx bx-check-circle" style="font-size: 40px; margin-top: 10px;" ></i>
              <h3 style="margin-top: 10px; margin-left: 30px;">{% trans 'Удобство и комфорт' %}</h3>
              </div>
              <h3 style="margin-top: 10px; margin-left: 10px; font-size: 25px;">{% trans 'Авторы' %}:</h3>
              <div class="user" style="display: flex; margin-top: 20px; margin-left: 10px;">
                <i class="bx bx-user" style="margin-top: 3px; margin-right: 5px;"></i>
                <h6>Карнаухов Сергей</h6>
                <i class="bx bx-user" style="margin-top: 3px; margin-right: 5px; margin-left: 10px;"></i>
                <h6>Станислав Орлов</h6>
              </div>
              <div class="user" style="display: flex; margin-top: 10px;">
                
              </div>
            </div>
            <div class="col-md-5">
                <br>

                <img src="{% static 'images/form-image.jpg' %}" class="img-fluid mt-4" alt="">
            </div>
          </div>
          
          </div>
    </main>
    <!-- модальное окно -->

{% endblock %}

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jocars</title>
    <link href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static './css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static './css/main.css' %}">
</head>
<body>

{% include 'layouts/header.html' %}


{% block content %}
{% endblock %}

{% include 'layouts/footer.html' %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static './js/popper.min.js' %}"></script>
<script src="{% static './js/bootstrap.min.js' %}"></script>
<script src="{% static './js/form.js' %}"></script>
</body>
</html>

templates/layouts/footer.html
{% load static %}
{% load i18n %}
      <!-- конец сайта  -->
      <footer>
          <div class="container">
            <div class="d-flex justify-content-between numbers">
                <p class="btn text-white font-weight-bold text-uppercase">8 (812) 123-45-67 | {% trans 'Работаем 7 дней в неделю' %} | 9:00 — 18:00</p>
                <div class="d-flex images">
                    <img src="{% static 'images/Instagram.svg' %}" style="width: 14px; height: 14px;" alt="">
                    <img src="{% static 'images/Youtube.svg' %}" style="width: 14px; height: 14px;" alt="">
                </div>
            </div>
          </div>
      </footer>

templates/layouts/header.html
{% load static %}
{% load tags %}
{% load i18n %}
<nav class="bg-light">
            <div class="container">
                <div class="navbar navbar-expand-md ">
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                          <li>
                            <div class="nav-item">
                              <h1>Jocar auto</h1>
                            </div>
                          </li>
                          <li class="nav-item active mt-2">
                            <a class="nav-link" href="{% url 'home:index' %}">Главная</a>
                          </li>
                          <li class="nav-item mt-2">
                            <a class="nav-link" href="{% url 'models:product' %}">Модели</a>
                          </li>
                        </ul>
                    </div>

                    <a href="{% url 'products:wishlist' %}"><img src="{% static './images/like.svg' %}" style="position:absolute;left:85%;top:35%" alt=""></a>


                </div>
            </div>
        </nav>
        <!-- header -->

templates/layouts/product-block.html
{% load tags %}
{% load static %}
{% load i18n %}
{% block content %}
        <div class="card" style="width: 22rem;height: 680px; box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;">
            <img class="card-img-top" src="{{ product.image.url }}" style="width: 100%;height:250px" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ product.model }}</h5>
                <p class="card-text">
                    {% trans 'Характеристики' %}:
                    <p> {% trans 'Объем' %} – {{ product.volume}}</p>
                      <p>{% trans 'Мощность' %} - {{ product.power}}</p>
                      <p>{% trans 'Коробка' %} - {{ product.transmission}}</p>
                      <p>{% trans 'Тип двигателя' %} - {{ product.engine}}</p>
                      <p>{% trans 'Топливо' %} - {{ product.fuel}}</p>
                      <p>{% trans 'Привод' %} - {{ product.drive_unit}}</p>
                      <p>{% trans 'Разгон' %} - {{ product.overclocking}}</p>
                      <p>{% trans 'Расход' %} – {{ product.consumption}}</p>
                      <p>{% trans 'Макс.скорость' %}, км/ч – {{ product.max_speed}}</p>
                </p>
                          <a onclick="add_to_wishlist(this, {{ product.pk }})" class="card-link">
                            {% if product|in_wishlist:request %}
                            <button class="btn btn-like2" type="submit"><img src="{% static './images/red_active.svg' %}"
                                                                         alt=""></button>
                            {% else %}
                            <button class="btn btn-like2" type="submit"><img src="{% static './images/like.svg' %}" alt="">
                            </button>
                            {% endif %}
                        </a>
                <button data-toggle="modal" data-target="#exampleModal" class="btn btn-12" style="margin: 30px 0 20px 20px; font-weight: bold; font-size: 15px; color: #fff; "><span>{% trans 'Оставить заявку' %}</span><span>{% trans 'Оставить заявку' %}</span></button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">{% trans 'Оставить заявку' %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            <div class="container">
                                <form id="formID">
                                    <div class="form-group">
                                        <label for="fname">{% trans 'Имя' %}</label>
                                        <input type="text" class="fname form-control" id="fname" name="fname" placeholder="Ваша имя" required>
                                      </div>
                                    <div class="form-group">
                                      <label for="lname">Email</label>
                                      <input type="email" class="lname form-control" id="lname" name="lname" aria-describedby="emailHelp" placeholder="Введите ваш email" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="number">{% trans 'Номер' %}</label>
                                        <input type="number" class="number form-control" id="number" aria-describedby="emailHelp" placeholder="Введите ваш номер" required>
                                      </div>
                              <div class="form-group">
                                    <fieldset class="question" id="title" data-validation="vrule_btn_required">
                                        <input type="radio" class="radio_button" name="fav_language" value="BMW M3" id="HTML"><label for="HTML" class="single-line">BMW M3</label>
                                        <input type="radio" class="radio_button" name="fav_language" value="BMW X6" id="CSS"><label for="CSS" class="single-line">BMW X6</label>
                                        <input type="radio" class="radio_button" name="fav_language" value="BMW X5M" id="JavaScript"><label for="JavaScript" class="single-line">BMW X5M</label>
                                        <input type="radio" class="radio_button" name="fav_language" value="Mercedes AMG E63s" id="Mercedes AMG E63s" style="font-size: 13px"><label for="Mercedes AMG E63s" class="single-line" style="font-size: 13px">Mercedes AMG E63s</label>
                                        <input type="radio" class="radio_button" name="fav_language" value="Mercedes GTs" id="Mercedes GTs"><label for="Mercedes GTs" class="single-line">Mercedes GTs</label>
                                        <input type="radio" class="radio_button" name="fav_language" value="Mercedes G63" id="Mercedes G63"><label for="Mercedes G63" class="single-line">Mercedes G63</label>
                                        <span class="error-message"></span>
                                    </fieldset>
                                </div>
                                    <div class="modal-footer">
                                        <input type="submit" class="btn btn-primary" value="Submit">
                                        </div>
                                  </form>
                            </div>
                        </div>

                    </div>
                    </div>
                </div>
            </div>
        </div>
<br>

{% endblock %}